token: "DISCORD_TOKEN"
logging_level: "INFO" # ERROR, WARN, INFO, DEBUG, TRACE

# Users allowed to execute privileged commands, e.g. randomize_role
# bot_admins:
#   "TOKEN": "USERNAME"

non_admin_response: "Not a bot admin! If you're Griff, kindly fuck off!"