name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "${{ github.repository }}"
    steps:
    - uses: actions/checkout@v3
    - name: Log into Registry
      run: "docker login ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.REGISTRY_TOKEN }}"
    - name: Build the Docker image
      run: |
        echo "{TIME_TAG}={$(date +%s)}" >> "$GITHUB_ENV"
        docker build . -f Dockerfile \
          -t ${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.IMAGE_NAME }}:${{ env.TIME_TAG }} \
          -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
          -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.TIME_TAG }}
    - name: Push to registry
      run: |
        docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.TIME_TAG }}
